apiVersion: batch/v1
kind: CronJob
metadata:
  name: cert-sync
  namespace: cert-manager
spec:
  schedule: "0 3 * * *"  # Daily at 3 AM
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: sync
            image: alpine:3.19
            command:
            - /bin/sh
            - -c
            - |
              set -e
              apk add --no-cache openssh-client yq

              # Setup SSH
              mkdir -p ~/.ssh
              cp /ssh-key/ssh-privatekey ~/.ssh/id_ed25519
              chmod 600 ~/.ssh/id_ed25519
              ssh-keyscan -H $(yq eval '.hosts[0].host' /config/hosts.yaml) >> ~/.ssh/known_hosts

              # Read configuration
              export HOST=$(yq eval '.hosts[0].host' /config/hosts.yaml)
              export USER=$(yq eval '.hosts[0].user' /config/hosts.yaml)
              export CERT_PATH=$(yq eval '.hosts[0].cert_path' /config/hosts.yaml)
              export KEY_PATH=$(yq eval '.hosts[0].key_path' /config/hosts.yaml)
              export RELOAD_CMD=$(yq eval '.hosts[0].reload_command' /config/hosts.yaml)

              # Create remote directory
              ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "mkdir -p $(dirname ${CERT_PATH})"

              # Copy certificate files using SSH (Home Assistant OS doesn't support SCP)
              cat /certs/tls.crt | ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "cat > ${CERT_PATH}"
              cat /certs/tls.key | ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "cat > ${KEY_PATH}"

              # Set permissions
              ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "chmod 644 ${CERT_PATH} && chmod 600 ${KEY_PATH}"

              # Reload service if command specified
              if [ -n "${RELOAD_CMD}" ]; then
                ssh -o StrictHostKeyChecking=no ${USER}@${HOST} "${RELOAD_CMD}"
              fi

              echo "Certificate synced successfully to ${HOST}"
            volumeMounts:
            - name: certs
              mountPath: /certs
              readOnly: true
            - name: ssh-key
              mountPath: /ssh-key
              readOnly: true
            - name: config
              mountPath: /config
              readOnly: true
          volumes:
          - name: certs
            secret:
              secretName: int-oquinena-com-tls
          - name: ssh-key
            secret:
              secretName: cert-sync-ssh-key
              defaultMode: 0400
          - name: config
            configMap:
              name: cert-sync-hosts
